#!/usr/bin/env python3
"""Decide which TLA+ specs a change affects (docs/architecture.md sections 17.4 and 17.5).

Changed files come from --files, or from `git diff --name-only <merge-base>...HEAD` with --base,
plus uncommitted and untracked files with --worktree.

    select_specs.py --base origin/main                 # affected specs, one per line
    select_specs.py --base origin/main --github-output # writes specs, forward, backward, core to $GITHUB_OUTPUT
    select_specs.py --emit                             # regenerate tools/core-paths.txt, .github/labeler.yml
    select_specs.py --check                            # fail if the generated files are stale
"""

from __future__ import annotations

import argparse
import os
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import mapfile  # noqa: E402

CORE_PATHS_FILE = mapfile.REPO_ROOT / "tools" / "core-paths.txt"
LABELER_FILE = mapfile.REPO_ROOT / ".github" / "labeler.yml"
GENERATED_NOTE = "Generated by tools/tla/select_specs.py --emit from specs/tla/MAP.toml; do not edit."


def git_lines(*args: str) -> list[str]:
    output = subprocess.run(
        ["git", *args], cwd=mapfile.REPO_ROOT, capture_output=True, text=True, check=True
    ).stdout
    return [line for line in output.splitlines() if line]


def changed_files(base: str | None, worktree: bool) -> list[str]:
    files: set[str] = set()
    if base:
        merge_base = git_lines("merge-base", base, "HEAD")[0]
        files.update(git_lines("diff", "--name-only", f"{merge_base}...HEAD"))
    if worktree:
        files.update(git_lines("diff", "--name-only", "HEAD"))
        files.update(git_lines("ls-files", "--others", "--exclude-standard"))
    return sorted(files)


def affected_specs(files: list[str], spec_map: mapfile.SpecMap) -> list[str]:
    if any(mapfile.matches_any(f, spec_map.always) for f in files):
        return [s.name for s in spec_map.specs]
    selected = []
    for spec in spec_map.specs:
        own = (f"specs/tla/{spec.name}.tla", f"specs/tla/{spec.name}.cfg")
        if any(f in own or mapfile.matches_any(f, spec.paths) for f in files):
            selected.append(spec.name)
    return selected


def touches_core(files: list[str], spec_map: mapfile.SpecMap) -> bool:
    globs = spec_map.core_globs()
    return any(mapfile.matches_any(f, globs) for f in files)


def render_core_paths(spec_map: mapfile.SpecMap) -> str:
    return "# " + GENERATED_NOTE + "\n" + "\n".join(spec_map.core_globs()) + "\n"


def render_labeler(spec_map: mapfile.SpecMap) -> str:
    lines = [
        "# " + GENERATED_NOTE,
        "# Consumed by actions/labeler in .github/workflows/labeler.yml.",
        "core:",
        "  - changed-files:",
        "      - any-glob-to-any-file:",
    ]
    lines += [f"          - '{glob}'" for glob in spec_map.core_globs()]
    return "\n".join(lines) + "\n"


def generated_files(spec_map: mapfile.SpecMap) -> dict[Path, str]:
    return {CORE_PATHS_FILE: render_core_paths(spec_map), LABELER_FILE: render_labeler(spec_map)}


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Select TLA+ specs affected by a change")
    parser.add_argument("--base", help="compare HEAD with the merge-base of this ref")
    parser.add_argument("--worktree", action="store_true", help="include uncommitted changes")
    parser.add_argument("--files", nargs="*", help="explicit list of changed files")
    parser.add_argument("--all", action="store_true", help="select every spec")
    parser.add_argument("--github-output", action="store_true", help="write to $GITHUB_OUTPUT")
    parser.add_argument("--emit", action="store_true", help="regenerate derived files")
    parser.add_argument("--check", action="store_true", help="fail if derived files are stale")
    args = parser.parse_args(argv)

    spec_map = mapfile.load()

    if args.emit or args.check:
        stale = []
        for path, content in generated_files(spec_map).items():
            current = path.read_text() if path.exists() else None
            if current != content:
                if args.emit:
                    path.parent.mkdir(parents=True, exist_ok=True)
                    path.write_text(content)
                else:
                    stale.append(path.relative_to(mapfile.REPO_ROOT).as_posix())
        if stale:
            print("stale generated files (run tools/tla/select_specs.py --emit): " + ", ".join(stale))
            return 1
        return 0

    if args.all:
        files = []
        specs = [s.name for s in spec_map.specs]
        core = True
    else:
        files = list(args.files) if args.files is not None else changed_files(args.base, args.worktree)
        specs = affected_specs(files, spec_map)
        core = touches_core(files, spec_map)
        if core and not specs:
            print("select: warning: core paths changed but no spec maps them", file=sys.stderr)
    if args.github_output:
        with open(os.environ["GITHUB_OUTPUT"], "a", encoding="utf-8") as handle:
            forward = [n for n in specs if spec_map.spec(n).forward]
            backward = [n for n in specs if spec_map.spec(n).backward]
            handle.write(f"specs={' '.join(specs)}\n")
            handle.write(f"forward={' '.join(forward)}\n")
            handle.write(f"backward={' '.join(backward)}\n")
            handle.write(f"core={'true' if core else 'false'}\n")
    for name in specs:
        print(name)
    print(f"select: {len(files)} changed file(s), {len(specs)} spec(s), core={core}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
