------------------------- MODULE OrderLifecycleTrace -------------------------
(* Generated by `jarvis trace-export --spec OrderLifecycle`; do not edit.        *)
(* Every order of one event log, its events in log order as OrderLifecycle       *)
(* actions (jarvis/node/trace_export.hpp). A refused step is an event the        *)
(* implementation refused, which the spec must not enable. Each step also holds  *)
(* the implementation's order after it, which the spec's must equal. TLC         *)
(* deadlocks at the first step that fails; tools/tla/check_trace.py names it.    *)
(* log: run *)
EXTENDS OrderLifecycle, Sequences, TLC

VARIABLES o, k

Orders == <<
  [id |-> "golden-000001-00000001", quantity |-> 1, steps |-> <<
      [seq |-> "8", refused |-> FALSE, a |-> <<"Plain", "SUBMITTED">>, status |-> "SUBMITTED", prev |-> "INITIALIZED", quantity |-> 1, filled |-> 0],
      [seq |-> "10", refused |-> FALSE, a |-> <<"Plain", "ACCEPTED">>, status |-> "ACCEPTED", prev |-> "SUBMITTED", quantity |-> 1, filled |-> 0],
      [seq |-> "15", refused |-> FALSE, a |-> <<"Plain", "PENDING_UPDATE">>, status |-> "PENDING_UPDATE", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0],
      [seq |-> "17", refused |-> FALSE, a |-> <<"Updated", 1>>, status |-> "ACCEPTED", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0],
      [seq |-> "23", refused |-> FALSE, a |-> <<"Plain", "PENDING_UPDATE">>, status |-> "PENDING_UPDATE", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0],
      [seq |-> "25", refused |-> FALSE, a |-> <<"Updated", 1>>, status |-> "ACCEPTED", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0],
      [seq |-> "32", refused |-> FALSE, a |-> <<"Plain", "PENDING_UPDATE">>, status |-> "PENDING_UPDATE", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0],
      [seq |-> "34", refused |-> FALSE, a |-> <<"Fill", "T1", 1>>, status |-> "FILLED", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 1],
      [seq |-> "36", refused |-> TRUE, a |-> <<"Plain", "MODIFY_REJECTED">>, status |-> "FILLED", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 1]>>]
, [id |-> "golden-000001-00000002", quantity |-> 1, steps |-> <<
      [seq |-> "8", refused |-> FALSE, a |-> <<"Plain", "SUBMITTED">>, status |-> "SUBMITTED", prev |-> "INITIALIZED", quantity |-> 1, filled |-> 0],
      [seq |-> "12", refused |-> FALSE, a |-> <<"Plain", "ACCEPTED">>, status |-> "ACCEPTED", prev |-> "SUBMITTED", quantity |-> 1, filled |-> 0],
      [seq |-> "15", refused |-> FALSE, a |-> <<"Plain", "PENDING_UPDATE">>, status |-> "PENDING_UPDATE", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0],
      [seq |-> "19", refused |-> FALSE, a |-> <<"Updated", 1>>, status |-> "ACCEPTED", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0],
      [seq |-> "23", refused |-> FALSE, a |-> <<"Plain", "PENDING_UPDATE">>, status |-> "PENDING_UPDATE", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0],
      [seq |-> "27", refused |-> FALSE, a |-> <<"Updated", 1>>, status |-> "ACCEPTED", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0],
      [seq |-> "32", refused |-> FALSE, a |-> <<"Plain", "PENDING_UPDATE">>, status |-> "PENDING_UPDATE", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0],
      [seq |-> "38", refused |-> FALSE, a |-> <<"Updated", 1>>, status |-> "ACCEPTED", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0],
      [seq |-> "42", refused |-> FALSE, a |-> <<"Plain", "PENDING_UPDATE">>, status |-> "PENDING_UPDATE", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0],
      [seq |-> "45", refused |-> FALSE, a |-> <<"Updated", 1>>, status |-> "ACCEPTED", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0],
      [seq |-> "48", refused |-> FALSE, a |-> <<"Plain", "PENDING_UPDATE">>, status |-> "PENDING_UPDATE", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0],
      [seq |-> "54", refused |-> FALSE, a |-> <<"Updated", 1>>, status |-> "ACCEPTED", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0],
      [seq |-> "56", refused |-> FALSE, a |-> <<"Plain", "PENDING_CANCEL">>, status |-> "PENDING_CANCEL", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0],
      [seq |-> "58", refused |-> FALSE, a |-> <<"Fill", "T3", 1>>, status |-> "FILLED", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 1],
      [seq |-> "60", refused |-> TRUE, a |-> <<"Plain", "CANCEL_REJECTED">>, status |-> "FILLED", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 1]>>]
, [id |-> "golden-000001-00000003", quantity |-> 1, steps |-> <<
      [seq |-> "42", refused |-> FALSE, a |-> <<"Plain", "SUBMITTED">>, status |-> "SUBMITTED", prev |-> "INITIALIZED", quantity |-> 1, filled |-> 0],
      [seq |-> "44", refused |-> FALSE, a |-> <<"Plain", "ACCEPTED">>, status |-> "ACCEPTED", prev |-> "SUBMITTED", quantity |-> 1, filled |-> 0],
      [seq |-> "48", refused |-> FALSE, a |-> <<"Plain", "PENDING_UPDATE">>, status |-> "PENDING_UPDATE", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0],
      [seq |-> "50", refused |-> FALSE, a |-> <<"Fill", "T2", 1>>, status |-> "FILLED", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 1],
      [seq |-> "52", refused |-> TRUE, a |-> <<"Plain", "MODIFY_REJECTED">>, status |-> "FILLED", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 1]>>]
, [id |-> "golden-000001-00000004", quantity |-> 1, steps |-> <<
      [seq |-> "65", refused |-> FALSE, a |-> <<"Plain", "SUBMITTED">>, status |-> "SUBMITTED", prev |-> "INITIALIZED", quantity |-> 1, filled |-> 0],
      [seq |-> "67", refused |-> FALSE, a |-> <<"Plain", "ACCEPTED">>, status |-> "ACCEPTED", prev |-> "SUBMITTED", quantity |-> 1, filled |-> 0],
      [seq |-> "78", refused |-> FALSE, a |-> <<"Fill", "T4", 1>>, status |-> "FILLED", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 1]>>]
, [id |-> "golden-000001-00000005", quantity |-> 1, steps |-> <<
      [seq |-> "65", refused |-> FALSE, a |-> <<"Plain", "SUBMITTED">>, status |-> "SUBMITTED", prev |-> "INITIALIZED", quantity |-> 1, filled |-> 0],
      [seq |-> "69", refused |-> FALSE, a |-> <<"Plain", "ACCEPTED">>, status |-> "ACCEPTED", prev |-> "SUBMITTED", quantity |-> 1, filled |-> 0],
      [seq |-> "88", refused |-> FALSE, a |-> <<"Fill", "T5", 1>>, status |-> "FILLED", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 1]>>]
, [id |-> "golden-000001-00000006", quantity |-> 1, steps |-> <<
      [seq |-> "82", refused |-> FALSE, a |-> <<"Plain", "SUBMITTED">>, status |-> "SUBMITTED", prev |-> "INITIALIZED", quantity |-> 1, filled |-> 0],
      [seq |-> "84", refused |-> FALSE, a |-> <<"Plain", "ACCEPTED">>, status |-> "ACCEPTED", prev |-> "SUBMITTED", quantity |-> 1, filled |-> 0],
      [seq |-> "90", refused |-> FALSE, a |-> <<"Plain", "PENDING_UPDATE">>, status |-> "PENDING_UPDATE", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0],
      [seq |-> "92", refused |-> FALSE, a |-> <<"Updated", 1>>, status |-> "ACCEPTED", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0],
      [seq |-> "100", refused |-> FALSE, a |-> <<"Plain", "PENDING_UPDATE">>, status |-> "PENDING_UPDATE", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0],
      [seq |-> "104", refused |-> FALSE, a |-> <<"Updated", 1>>, status |-> "ACCEPTED", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0],
      [seq |-> "112", refused |-> FALSE, a |-> <<"Plain", "PENDING_UPDATE">>, status |-> "PENDING_UPDATE", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0],
      [seq |-> "114", refused |-> FALSE, a |-> <<"Fill", "T7", 1>>, status |-> "FILLED", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 1],
      [seq |-> "116", refused |-> TRUE, a |-> <<"Plain", "MODIFY_REJECTED">>, status |-> "FILLED", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 1]>>]
, [id |-> "golden-000001-00000007", quantity |-> 1, steps |-> <<
      [seq |-> "90", refused |-> FALSE, a |-> <<"Plain", "SUBMITTED">>, status |-> "SUBMITTED", prev |-> "INITIALIZED", quantity |-> 1, filled |-> 0],
      [seq |-> "93", refused |-> FALSE, a |-> <<"Plain", "ACCEPTED">>, status |-> "ACCEPTED", prev |-> "SUBMITTED", quantity |-> 1, filled |-> 0],
      [seq |-> "100", refused |-> FALSE, a |-> <<"Plain", "PENDING_UPDATE">>, status |-> "PENDING_UPDATE", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0],
      [seq |-> "102", refused |-> FALSE, a |-> <<"Fill", "T6", 1>>, status |-> "FILLED", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 1],
      [seq |-> "105", refused |-> TRUE, a |-> <<"Plain", "MODIFY_REJECTED">>, status |-> "FILLED", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 1]>>]
, [id |-> "golden-000001-00000008", quantity |-> 1, steps |-> <<
      [seq |-> "90", refused |-> FALSE, a |-> <<"Plain", "SUBMITTED">>, status |-> "SUBMITTED", prev |-> "INITIALIZED", quantity |-> 1, filled |-> 0],
      [seq |-> "94", refused |-> FALSE, a |-> <<"Plain", "REJECTED">>, status |-> "REJECTED", prev |-> "SUBMITTED", quantity |-> 1, filled |-> 0]>>]
, [id |-> "golden-000001-00000009", quantity |-> 1, steps |-> <<
      [seq |-> "112", refused |-> FALSE, a |-> <<"Plain", "SUBMITTED">>, status |-> "SUBMITTED", prev |-> "INITIALIZED", quantity |-> 1, filled |-> 0],
      [seq |-> "118", refused |-> FALSE, a |-> <<"Plain", "ACCEPTED">>, status |-> "ACCEPTED", prev |-> "SUBMITTED", quantity |-> 1, filled |-> 0],
      [seq |-> "128", refused |-> FALSE, a |-> <<"Plain", "PENDING_CANCEL">>, status |-> "PENDING_CANCEL", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0],
      [seq |-> "130", refused |-> FALSE, a |-> <<"Plain", "CANCELED">>, status |-> "CANCELED", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0]>>]
, [id |-> "golden-000001-0000000A", quantity |-> 1, steps |-> <<
      [seq |-> "112", refused |-> FALSE, a |-> <<"Plain", "SUBMITTED">>, status |-> "SUBMITTED", prev |-> "INITIALIZED", quantity |-> 1, filled |-> 0],
      [seq |-> "120", refused |-> FALSE, a |-> <<"Plain", "ACCEPTED">>, status |-> "ACCEPTED", prev |-> "SUBMITTED", quantity |-> 1, filled |-> 0],
      [seq |-> "121", refused |-> FALSE, a |-> <<"Fill", "T8", 1>>, status |-> "FILLED", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 1]>>]
, [id |-> "golden-000001-0000000B", quantity |-> 1, steps |-> <<
      [seq |-> "135", refused |-> FALSE, a |-> <<"Plain", "SUBMITTED">>, status |-> "SUBMITTED", prev |-> "INITIALIZED", quantity |-> 1, filled |-> 0],
      [seq |-> "137", refused |-> FALSE, a |-> <<"Plain", "ACCEPTED">>, status |-> "ACCEPTED", prev |-> "SUBMITTED", quantity |-> 1, filled |-> 0],
      [seq |-> "147", refused |-> FALSE, a |-> <<"Plain", "PENDING_UPDATE">>, status |-> "PENDING_UPDATE", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0],
      [seq |-> "149", refused |-> FALSE, a |-> <<"Fill", "T10", 1>>, status |-> "FILLED", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 1],
      [seq |-> "151", refused |-> TRUE, a |-> <<"Plain", "MODIFY_REJECTED">>, status |-> "FILLED", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 1]>>]
, [id |-> "golden-000001-0000000C", quantity |-> 1, steps |-> <<
      [seq |-> "135", refused |-> FALSE, a |-> <<"Plain", "SUBMITTED">>, status |-> "SUBMITTED", prev |-> "INITIALIZED", quantity |-> 1, filled |-> 0],
      [seq |-> "138", refused |-> FALSE, a |-> <<"Plain", "ACCEPTED">>, status |-> "ACCEPTED", prev |-> "SUBMITTED", quantity |-> 1, filled |-> 0],
      [seq |-> "143", refused |-> FALSE, a |-> <<"Fill", "T9", 1>>, status |-> "FILLED", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 1]>>]
, [id |-> "golden-000001-0000000D", quantity |-> 1, steps |-> <<
      [seq |-> "147", refused |-> FALSE, a |-> <<"Plain", "SUBMITTED">>, status |-> "SUBMITTED", prev |-> "INITIALIZED", quantity |-> 1, filled |-> 0],
      [seq |-> "152", refused |-> FALSE, a |-> <<"Plain", "ACCEPTED">>, status |-> "ACCEPTED", prev |-> "SUBMITTED", quantity |-> 1, filled |-> 0],
      [seq |-> "156", refused |-> FALSE, a |-> <<"Plain", "PENDING_UPDATE">>, status |-> "PENDING_UPDATE", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0],
      [seq |-> "160", refused |-> FALSE, a |-> <<"Updated", 1>>, status |-> "ACCEPTED", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0],
      [seq |-> "178", refused |-> FALSE, a |-> <<"Plain", "PENDING_UPDATE">>, status |-> "PENDING_UPDATE", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0],
      [seq |-> "182", refused |-> FALSE, a |-> <<"Updated", 1>>, status |-> "ACCEPTED", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0],
      [seq |-> "186", refused |-> FALSE, a |-> <<"Fill", "T12", 1>>, status |-> "FILLED", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 1]>>]
, [id |-> "golden-000001-0000000E", quantity |-> 1, steps |-> <<
      [seq |-> "156", refused |-> FALSE, a |-> <<"Plain", "SUBMITTED">>, status |-> "SUBMITTED", prev |-> "INITIALIZED", quantity |-> 1, filled |-> 0],
      [seq |-> "158", refused |-> FALSE, a |-> <<"Plain", "ACCEPTED">>, status |-> "ACCEPTED", prev |-> "SUBMITTED", quantity |-> 1, filled |-> 0],
      [seq |-> "174", refused |-> FALSE, a |-> <<"Fill", "T11", 1>>, status |-> "FILLED", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 1]>>]
, [id |-> "golden-000001-0000000F", quantity |-> 1, steps |-> <<
      [seq |-> "156", refused |-> FALSE, a |-> <<"Plain", "SUBMITTED">>, status |-> "SUBMITTED", prev |-> "INITIALIZED", quantity |-> 1, filled |-> 0],
      [seq |-> "161", refused |-> FALSE, a |-> <<"Plain", "ACCEPTED">>, status |-> "ACCEPTED", prev |-> "SUBMITTED", quantity |-> 1, filled |-> 0],
      [seq |-> "162", refused |-> FALSE, a |-> <<"Plain", "EXPIRED">>, status |-> "EXPIRED", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0]>>]
, [id |-> "golden-000001-0000000G", quantity |-> 1, steps |-> <<
      [seq |-> "178", refused |-> FALSE, a |-> <<"Plain", "SUBMITTED">>, status |-> "SUBMITTED", prev |-> "INITIALIZED", quantity |-> 1, filled |-> 0],
      [seq |-> "180", refused |-> FALSE, a |-> <<"Plain", "ACCEPTED">>, status |-> "ACCEPTED", prev |-> "SUBMITTED", quantity |-> 1, filled |-> 0],
      [seq |-> "190", refused |-> FALSE, a |-> <<"Plain", "PENDING_UPDATE">>, status |-> "PENDING_UPDATE", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0],
      [seq |-> "192", refused |-> FALSE, a |-> <<"Updated", 1>>, status |-> "ACCEPTED", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0],
      [seq |-> "196", refused |-> FALSE, a |-> <<"Plain", "PENDING_CANCEL">>, status |-> "PENDING_CANCEL", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0],
      [seq |-> "198", refused |-> FALSE, a |-> <<"Plain", "CANCELED">>, status |-> "CANCELED", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0]>>]
, [id |-> "golden-000001-0000000H", quantity |-> 1, steps |-> <<
      [seq |-> "178", refused |-> FALSE, a |-> <<"Plain", "DENIED">>, status |-> "DENIED", prev |-> "INITIALIZED", quantity |-> 1, filled |-> 0]>>]
, [id |-> "golden-000001-0000000J", quantity |-> 1, steps |-> <<
      [seq |-> "190", refused |-> FALSE, a |-> <<"Plain", "SUBMITTED">>, status |-> "SUBMITTED", prev |-> "INITIALIZED", quantity |-> 1, filled |-> 0],
      [seq |-> "194", refused |-> FALSE, a |-> <<"Plain", "ACCEPTED">>, status |-> "ACCEPTED", prev |-> "SUBMITTED", quantity |-> 1, filled |-> 0],
      [seq |-> "196", refused |-> FALSE, a |-> <<"Plain", "PENDING_CANCEL">>, status |-> "PENDING_CANCEL", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0],
      [seq |-> "200", refused |-> FALSE, a |-> <<"Plain", "CANCELED">>, status |-> "CANCELED", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0]>>]
, [id |-> "golden-000001-0000000K", quantity |-> 1, steps |-> <<
      [seq |-> "206", refused |-> FALSE, a |-> <<"Plain", "SUBMITTED">>, status |-> "SUBMITTED", prev |-> "INITIALIZED", quantity |-> 1, filled |-> 0],
      [seq |-> "208", refused |-> FALSE, a |-> <<"Plain", "ACCEPTED">>, status |-> "ACCEPTED", prev |-> "SUBMITTED", quantity |-> 1, filled |-> 0],
      [seq |-> "219", refused |-> FALSE, a |-> <<"Plain", "PENDING_UPDATE">>, status |-> "PENDING_UPDATE", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0],
      [seq |-> "219", refused |-> FALSE, a |-> <<"Plain", "PENDING_UPDATE">>, status |-> "PENDING_UPDATE", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0],
      [seq |-> "221", refused |-> FALSE, a |-> <<"Fill", "T13", 1>>, status |-> "FILLED", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 1],
      [seq |-> "223", refused |-> TRUE, a |-> <<"Plain", "MODIFY_REJECTED">>, status |-> "FILLED", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 1],
      [seq |-> "226", refused |-> TRUE, a |-> <<"Plain", "MODIFY_REJECTED">>, status |-> "FILLED", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 1]>>]
, [id |-> "golden-000001-0000000M", quantity |-> 1, steps |-> <<
      [seq |-> "206", refused |-> FALSE, a |-> <<"Plain", "SUBMITTED">>, status |-> "SUBMITTED", prev |-> "INITIALIZED", quantity |-> 1, filled |-> 0],
      [seq |-> "210", refused |-> FALSE, a |-> <<"Plain", "ACCEPTED">>, status |-> "ACCEPTED", prev |-> "SUBMITTED", quantity |-> 1, filled |-> 0],
      [seq |-> "219", refused |-> FALSE, a |-> <<"Plain", "PENDING_UPDATE">>, status |-> "PENDING_UPDATE", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0],
      [seq |-> "225", refused |-> FALSE, a |-> <<"Updated", 1>>, status |-> "ACCEPTED", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0],
      [seq |-> "233", refused |-> FALSE, a |-> <<"Plain", "PENDING_UPDATE">>, status |-> "PENDING_UPDATE", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0],
      [seq |-> "237", refused |-> FALSE, a |-> <<"Updated", 1>>, status |-> "ACCEPTED", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0],
      [seq |-> "247", refused |-> FALSE, a |-> <<"Plain", "PENDING_UPDATE">>, status |-> "PENDING_UPDATE", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0],
      [seq |-> "253", refused |-> FALSE, a |-> <<"Updated", 1>>, status |-> "ACCEPTED", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0],
      [seq |-> "259", refused |-> FALSE, a |-> <<"Plain", "PENDING_UPDATE">>, status |-> "PENDING_UPDATE", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0],
      [seq |-> "262", refused |-> FALSE, a |-> <<"Updated", 1>>, status |-> "ACCEPTED", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0],
      [seq |-> "264", refused |-> FALSE, a |-> <<"Plain", "PENDING_CANCEL">>, status |-> "PENDING_CANCEL", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0],
      [seq |-> "268", refused |-> FALSE, a |-> <<"Plain", "CANCELED">>, status |-> "CANCELED", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0]>>]
, [id |-> "golden-000001-0000000N", quantity |-> 1, steps |-> <<
      [seq |-> "206", refused |-> FALSE, a |-> <<"Plain", "SUBMITTED">>, status |-> "SUBMITTED", prev |-> "INITIALIZED", quantity |-> 1, filled |-> 0],
      [seq |-> "211", refused |-> FALSE, a |-> <<"Plain", "REJECTED">>, status |-> "REJECTED", prev |-> "SUBMITTED", quantity |-> 1, filled |-> 0]>>]
, [id |-> "golden-000001-0000000P", quantity |-> 1, steps |-> <<
      [seq |-> "233", refused |-> FALSE, a |-> <<"Plain", "SUBMITTED">>, status |-> "SUBMITTED", prev |-> "INITIALIZED", quantity |-> 1, filled |-> 0],
      [seq |-> "235", refused |-> FALSE, a |-> <<"Plain", "ACCEPTED">>, status |-> "ACCEPTED", prev |-> "SUBMITTED", quantity |-> 1, filled |-> 0],
      [seq |-> "247", refused |-> FALSE, a |-> <<"Plain", "PENDING_UPDATE">>, status |-> "PENDING_UPDATE", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0],
      [seq |-> "249", refused |-> FALSE, a |-> <<"Fill", "T14", 1>>, status |-> "FILLED", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 1],
      [seq |-> "251", refused |-> TRUE, a |-> <<"Plain", "MODIFY_REJECTED">>, status |-> "FILLED", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 1]>>]
, [id |-> "golden-000001-0000000Q", quantity |-> 1, steps |-> <<
      [seq |-> "247", refused |-> FALSE, a |-> <<"Plain", "SUBMITTED">>, status |-> "SUBMITTED", prev |-> "INITIALIZED", quantity |-> 1, filled |-> 0],
      [seq |-> "255", refused |-> FALSE, a |-> <<"Plain", "ACCEPTED">>, status |-> "ACCEPTED", prev |-> "SUBMITTED", quantity |-> 1, filled |-> 0],
      [seq |-> "257", refused |-> FALSE, a |-> <<"Fill", "T15", 1>>, status |-> "FILLED", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 1]>>]
, [id |-> "golden-000001-0000000R", quantity |-> 1, steps |-> <<
      [seq |-> "259", refused |-> FALSE, a |-> <<"Plain", "SUBMITTED">>, status |-> "SUBMITTED", prev |-> "INITIALIZED", quantity |-> 1, filled |-> 0],
      [seq |-> "261", refused |-> FALSE, a |-> <<"Plain", "ACCEPTED">>, status |-> "ACCEPTED", prev |-> "SUBMITTED", quantity |-> 1, filled |-> 0],
      [seq |-> "264", refused |-> FALSE, a |-> <<"Plain", "PENDING_CANCEL">>, status |-> "PENDING_CANCEL", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0],
      [seq |-> "266", refused |-> FALSE, a |-> <<"Fill", "T16", 1>>, status |-> "FILLED", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 1],
      [seq |-> "270", refused |-> TRUE, a |-> <<"Plain", "CANCEL_REJECTED">>, status |-> "FILLED", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 1]>>]
, [id |-> "golden-000001-0000000S", quantity |-> 1, steps |-> <<
      [seq |-> "279", refused |-> FALSE, a |-> <<"Plain", "SUBMITTED">>, status |-> "SUBMITTED", prev |-> "INITIALIZED", quantity |-> 1, filled |-> 0],
      [seq |-> "281", refused |-> FALSE, a |-> <<"Plain", "ACCEPTED">>, status |-> "ACCEPTED", prev |-> "SUBMITTED", quantity |-> 1, filled |-> 0],
      [seq |-> "290", refused |-> FALSE, a |-> <<"Plain", "PENDING_UPDATE">>, status |-> "PENDING_UPDATE", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0],
      [seq |-> "292", refused |-> FALSE, a |-> <<"Updated", 1>>, status |-> "ACCEPTED", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0],
      [seq |-> "298", refused |-> FALSE, a |-> <<"Plain", "PENDING_UPDATE">>, status |-> "PENDING_UPDATE", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0],
      [seq |-> "302", refused |-> FALSE, a |-> <<"Updated", 1>>, status |-> "ACCEPTED", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0],
      [seq |-> "314", refused |-> FALSE, a |-> <<"Plain", "PENDING_UPDATE">>, status |-> "PENDING_UPDATE", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0],
      [seq |-> "318", refused |-> FALSE, a |-> <<"Updated", 1>>, status |-> "ACCEPTED", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0],
      [seq |-> "325", refused |-> FALSE, a |-> <<"Plain", "PENDING_UPDATE">>, status |-> "PENDING_UPDATE", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0],
      [seq |-> "327", refused |-> FALSE, a |-> <<"Updated", 1>>, status |-> "ACCEPTED", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0],
      [seq |-> "339", refused |-> FALSE, a |-> <<"Plain", "PENDING_CANCEL">>, status |-> "PENDING_CANCEL", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0],
      [seq |-> "341", refused |-> FALSE, a |-> <<"Fill", "T19", 1>>, status |-> "FILLED", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 1],
      [seq |-> "343", refused |-> TRUE, a |-> <<"Plain", "CANCEL_REJECTED">>, status |-> "FILLED", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 1]>>]
, [id |-> "golden-000001-0000000T", quantity |-> 1, steps |-> <<
      [seq |-> "279", refused |-> FALSE, a |-> <<"Plain", "SUBMITTED">>, status |-> "SUBMITTED", prev |-> "INITIALIZED", quantity |-> 1, filled |-> 0],
      [seq |-> "283", refused |-> FALSE, a |-> <<"Plain", "ACCEPTED">>, status |-> "ACCEPTED", prev |-> "SUBMITTED", quantity |-> 1, filled |-> 0],
      [seq |-> "290", refused |-> FALSE, a |-> <<"Plain", "PENDING_UPDATE">>, status |-> "PENDING_UPDATE", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0],
      [seq |-> "294", refused |-> FALSE, a |-> <<"Updated", 1>>, status |-> "ACCEPTED", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0],
      [seq |-> "298", refused |-> FALSE, a |-> <<"Plain", "PENDING_UPDATE">>, status |-> "PENDING_UPDATE", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0],
      [seq |-> "300", refused |-> FALSE, a |-> <<"Fill", "T17", 1>>, status |-> "FILLED", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 1],
      [seq |-> "304", refused |-> TRUE, a |-> <<"Plain", "MODIFY_REJECTED">>, status |-> "FILLED", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 1]>>]
, [id |-> "golden-000001-0000000V", quantity |-> 1, steps |-> <<
      [seq |-> "307", refused |-> FALSE, a |-> <<"Plain", "SUBMITTED">>, status |-> "SUBMITTED", prev |-> "INITIALIZED", quantity |-> 1, filled |-> 0],
      [seq |-> "309", refused |-> FALSE, a |-> <<"Plain", "ACCEPTED">>, status |-> "ACCEPTED", prev |-> "SUBMITTED", quantity |-> 1, filled |-> 0],
      [seq |-> "314", refused |-> FALSE, a |-> <<"Plain", "PENDING_UPDATE">>, status |-> "PENDING_UPDATE", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0],
      [seq |-> "316", refused |-> FALSE, a |-> <<"Fill", "T18", 1>>, status |-> "FILLED", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 1],
      [seq |-> "319", refused |-> TRUE, a |-> <<"Plain", "MODIFY_REJECTED">>, status |-> "FILLED", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 1]>>]
, [id |-> "golden-000001-0000000W", quantity |-> 1, steps |-> <<
      [seq |-> "314", refused |-> FALSE, a |-> <<"Plain", "SUBMITTED">>, status |-> "SUBMITTED", prev |-> "INITIALIZED", quantity |-> 1, filled |-> 0],
      [seq |-> "320", refused |-> FALSE, a |-> <<"Plain", "REJECTED">>, status |-> "REJECTED", prev |-> "SUBMITTED", quantity |-> 1, filled |-> 0]>>]
, [id |-> "golden-000001-0000000X", quantity |-> 1, steps |-> <<
      [seq |-> "325", refused |-> FALSE, a |-> <<"Plain", "SUBMITTED">>, status |-> "SUBMITTED", prev |-> "INITIALIZED", quantity |-> 1, filled |-> 0],
      [seq |-> "329", refused |-> FALSE, a |-> <<"Plain", "ACCEPTED">>, status |-> "ACCEPTED", prev |-> "SUBMITTED", quantity |-> 1, filled |-> 0],
      [seq |-> "339", refused |-> FALSE, a |-> <<"Plain", "PENDING_CANCEL">>, status |-> "PENDING_CANCEL", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0],
      [seq |-> "344", refused |-> FALSE, a |-> <<"Plain", "CANCELED">>, status |-> "CANCELED", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0]>>]
, [id |-> "golden-000001-0000000Y", quantity |-> 1, steps |-> <<
      [seq |-> "325", refused |-> FALSE, a |-> <<"Plain", "SUBMITTED">>, status |-> "SUBMITTED", prev |-> "INITIALIZED", quantity |-> 1, filled |-> 0],
      [seq |-> "331", refused |-> FALSE, a |-> <<"Plain", "ACCEPTED">>, status |-> "ACCEPTED", prev |-> "SUBMITTED", quantity |-> 1, filled |-> 0],
      [seq |-> "332", refused |-> FALSE, a |-> <<"Plain", "EXPIRED">>, status |-> "EXPIRED", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0]>>]
, [id |-> "golden-000001-0000000Z", quantity |-> 1, steps |-> <<
      [seq |-> "352", refused |-> FALSE, a |-> <<"Plain", "SUBMITTED">>, status |-> "SUBMITTED", prev |-> "INITIALIZED", quantity |-> 1, filled |-> 0],
      [seq |-> "354", refused |-> FALSE, a |-> <<"Plain", "ACCEPTED">>, status |-> "ACCEPTED", prev |-> "SUBMITTED", quantity |-> 1, filled |-> 0],
      [seq |-> "364", refused |-> FALSE, a |-> <<"Plain", "PENDING_UPDATE">>, status |-> "PENDING_UPDATE", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0],
      [seq |-> "366", refused |-> FALSE, a |-> <<"Updated", 1>>, status |-> "ACCEPTED", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0],
      [seq |-> "371", refused |-> FALSE, a |-> <<"Fill", "T20", 1>>, status |-> "FILLED", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 1]>>]
, [id |-> "golden-000001-00000010", quantity |-> 1, steps |-> <<
      [seq |-> "352", refused |-> FALSE, a |-> <<"Plain", "SUBMITTED">>, status |-> "SUBMITTED", prev |-> "INITIALIZED", quantity |-> 1, filled |-> 0],
      [seq |-> "355", refused |-> FALSE, a |-> <<"Plain", "ACCEPTED">>, status |-> "ACCEPTED", prev |-> "SUBMITTED", quantity |-> 1, filled |-> 0],
      [seq |-> "364", refused |-> FALSE, a |-> <<"Plain", "PENDING_UPDATE">>, status |-> "PENDING_UPDATE", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0],
      [seq |-> "367", refused |-> FALSE, a |-> <<"Updated", 1>>, status |-> "ACCEPTED", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0],
      [seq |-> "375", refused |-> FALSE, a |-> <<"Plain", "PENDING_UPDATE">>, status |-> "PENDING_UPDATE", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0],
      [seq |-> "378", refused |-> FALSE, a |-> <<"Updated", 1>>, status |-> "ACCEPTED", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0],
      [seq |-> "402", refused |-> FALSE, a |-> <<"Plain", "PENDING_CANCEL">>, status |-> "PENDING_CANCEL", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0],
      [seq |-> "404", refused |-> FALSE, a |-> <<"Plain", "CANCELED">>, status |-> "CANCELED", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0]>>]
, [id |-> "golden-000001-00000011", quantity |-> 1, steps |-> <<
      [seq |-> "364", refused |-> FALSE, a |-> <<"Plain", "DENIED">>, status |-> "DENIED", prev |-> "INITIALIZED", quantity |-> 1, filled |-> 0]>>]
, [id |-> "golden-000001-00000012", quantity |-> 1, steps |-> <<
      [seq |-> "375", refused |-> FALSE, a |-> <<"Plain", "SUBMITTED">>, status |-> "SUBMITTED", prev |-> "INITIALIZED", quantity |-> 1, filled |-> 0],
      [seq |-> "377", refused |-> FALSE, a |-> <<"Plain", "ACCEPTED">>, status |-> "ACCEPTED", prev |-> "SUBMITTED", quantity |-> 1, filled |-> 0],
      [seq |-> "402", refused |-> FALSE, a |-> <<"Plain", "PENDING_CANCEL">>, status |-> "PENDING_CANCEL", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0],
      [seq |-> "406", refused |-> FALSE, a |-> <<"Plain", "CANCELED">>, status |-> "CANCELED", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0]>>]
, [id |-> "golden-000001-00000013", quantity |-> 1, steps |-> <<
      [seq |-> "375", refused |-> FALSE, a |-> <<"Plain", "SUBMITTED">>, status |-> "SUBMITTED", prev |-> "INITIALIZED", quantity |-> 1, filled |-> 0],
      [seq |-> "380", refused |-> FALSE, a |-> <<"Plain", "ACCEPTED">>, status |-> "ACCEPTED", prev |-> "SUBMITTED", quantity |-> 1, filled |-> 0],
      [seq |-> "382", refused |-> FALSE, a |-> <<"Fill", "T21", 1>>, status |-> "FILLED", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 1]>>]
, [id |-> "golden-000001-00000014", quantity |-> 1, steps |-> <<
      [seq |-> "408", refused |-> FALSE, a |-> <<"Plain", "SUBMITTED">>, status |-> "SUBMITTED", prev |-> "INITIALIZED", quantity |-> 1, filled |-> 0],
      [seq |-> "410", refused |-> FALSE, a |-> <<"Plain", "ACCEPTED">>, status |-> "ACCEPTED", prev |-> "SUBMITTED", quantity |-> 1, filled |-> 0],
      [seq |-> "417", refused |-> FALSE, a |-> <<"Plain", "PENDING_UPDATE">>, status |-> "PENDING_UPDATE", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0],
      [seq |-> "419", refused |-> FALSE, a |-> <<"Fill", "T22", 1>>, status |-> "FILLED", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 1],
      [seq |-> "421", refused |-> TRUE, a |-> <<"Plain", "MODIFY_REJECTED">>, status |-> "FILLED", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 1]>>]
, [id |-> "golden-000001-00000015", quantity |-> 1, steps |-> <<
      [seq |-> "408", refused |-> FALSE, a |-> <<"Plain", "SUBMITTED">>, status |-> "SUBMITTED", prev |-> "INITIALIZED", quantity |-> 1, filled |-> 0],
      [seq |-> "412", refused |-> FALSE, a |-> <<"Plain", "ACCEPTED">>, status |-> "ACCEPTED", prev |-> "SUBMITTED", quantity |-> 1, filled |-> 0],
      [seq |-> "417", refused |-> FALSE, a |-> <<"Plain", "PENDING_UPDATE">>, status |-> "PENDING_UPDATE", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0],
      [seq |-> "422", refused |-> FALSE, a |-> <<"Updated", 1>>, status |-> "ACCEPTED", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0],
      [seq |-> "438", refused |-> FALSE, a |-> <<"Plain", "PENDING_UPDATE">>, status |-> "PENDING_UPDATE", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0],
      [seq |-> "440", refused |-> FALSE, a |-> <<"Fill", "T23", 1>>, status |-> "FILLED", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 1],
      [seq |-> "444", refused |-> TRUE, a |-> <<"Plain", "MODIFY_REJECTED">>, status |-> "FILLED", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 1]>>]
, [id |-> "golden-000001-00000016", quantity |-> 1, steps |-> <<
      [seq |-> "417", refused |-> FALSE, a |-> <<"Plain", "SUBMITTED">>, status |-> "SUBMITTED", prev |-> "INITIALIZED", quantity |-> 1, filled |-> 0],
      [seq |-> "423", refused |-> FALSE, a |-> <<"Plain", "REJECTED">>, status |-> "REJECTED", prev |-> "SUBMITTED", quantity |-> 1, filled |-> 0]>>]
, [id |-> "golden-000001-00000017", quantity |-> 1, steps |-> <<
      [seq |-> "428", refused |-> FALSE, a |-> <<"Plain", "SUBMITTED">>, status |-> "SUBMITTED", prev |-> "INITIALIZED", quantity |-> 1, filled |-> 0],
      [seq |-> "430", refused |-> FALSE, a |-> <<"Plain", "ACCEPTED">>, status |-> "ACCEPTED", prev |-> "SUBMITTED", quantity |-> 1, filled |-> 0],
      [seq |-> "438", refused |-> FALSE, a |-> <<"Plain", "PENDING_UPDATE">>, status |-> "PENDING_UPDATE", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0],
      [seq |-> "438", refused |-> FALSE, a |-> <<"Plain", "PENDING_UPDATE">>, status |-> "PENDING_UPDATE", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0],
      [seq |-> "442", refused |-> FALSE, a |-> <<"Updated", 1>>, status |-> "ACCEPTED", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0],
      [seq |-> "446", refused |-> FALSE, a |-> <<"Updated", 2>>, status |-> "ACCEPTED", prev |-> "ACCEPTED", quantity |-> 2, filled |-> 0],
      [seq |-> "450", refused |-> FALSE, a |-> <<"Plain", "PENDING_UPDATE">>, status |-> "PENDING_UPDATE", prev |-> "ACCEPTED", quantity |-> 2, filled |-> 0],
      [seq |-> "452", refused |-> FALSE, a |-> <<"Updated", 2>>, status |-> "ACCEPTED", prev |-> "ACCEPTED", quantity |-> 2, filled |-> 0],
      [seq |-> "465", refused |-> FALSE, a |-> <<"Fill", "T24", 2>>, status |-> "FILLED", prev |-> "ACCEPTED", quantity |-> 2, filled |-> 2]>>]
, [id |-> "golden-000001-00000018", quantity |-> 1, steps |-> <<
      [seq |-> "450", refused |-> FALSE, a |-> <<"Plain", "SUBMITTED">>, status |-> "SUBMITTED", prev |-> "INITIALIZED", quantity |-> 1, filled |-> 0],
      [seq |-> "454", refused |-> FALSE, a |-> <<"Plain", "ACCEPTED">>, status |-> "ACCEPTED", prev |-> "SUBMITTED", quantity |-> 1, filled |-> 0],
      [seq |-> "467", refused |-> FALSE, a |-> <<"Plain", "PENDING_CANCEL">>, status |-> "PENDING_CANCEL", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0],
      [seq |-> "469", refused |-> FALSE, a |-> <<"Plain", "CANCELED">>, status |-> "CANCELED", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0]>>]
, [id |-> "golden-000001-00000019", quantity |-> 1, steps |-> <<
      [seq |-> "475", refused |-> FALSE, a |-> <<"Plain", "SUBMITTED">>, status |-> "SUBMITTED", prev |-> "INITIALIZED", quantity |-> 1, filled |-> 0],
      [seq |-> "477", refused |-> FALSE, a |-> <<"Plain", "ACCEPTED">>, status |-> "ACCEPTED", prev |-> "SUBMITTED", quantity |-> 1, filled |-> 0],
      [seq |-> "480", refused |-> FALSE, a |-> <<"Plain", "PENDING_UPDATE">>, status |-> "PENDING_UPDATE", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0],
      [seq |-> "482", refused |-> FALSE, a |-> <<"Updated", 1>>, status |-> "ACCEPTED", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0],
      [seq |-> "492", refused |-> FALSE, a |-> <<"Plain", "PENDING_UPDATE">>, status |-> "PENDING_UPDATE", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0],
      [seq |-> "494", refused |-> FALSE, a |-> <<"Updated", 1>>, status |-> "ACCEPTED", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0],
      [seq |-> "505", refused |-> FALSE, a |-> <<"Plain", "PENDING_UPDATE">>, status |-> "PENDING_UPDATE", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0],
      [seq |-> "507", refused |-> FALSE, a |-> <<"Fill", "T26", 1>>, status |-> "FILLED", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 1],
      [seq |-> "509", refused |-> TRUE, a |-> <<"Plain", "MODIFY_REJECTED">>, status |-> "FILLED", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 1]>>]
, [id |-> "golden-000001-0000001A", quantity |-> 1, steps |-> <<
      [seq |-> "475", refused |-> FALSE, a |-> <<"Plain", "SUBMITTED">>, status |-> "SUBMITTED", prev |-> "INITIALIZED", quantity |-> 1, filled |-> 0],
      [seq |-> "478", refused |-> FALSE, a |-> <<"Plain", "ACCEPTED">>, status |-> "ACCEPTED", prev |-> "SUBMITTED", quantity |-> 1, filled |-> 0],
      [seq |-> "480", refused |-> FALSE, a |-> <<"Plain", "PENDING_UPDATE">>, status |-> "PENDING_UPDATE", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0],
      [seq |-> "484", refused |-> FALSE, a |-> <<"Updated", 1>>, status |-> "ACCEPTED", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0],
      [seq |-> "492", refused |-> FALSE, a |-> <<"Plain", "PENDING_UPDATE">>, status |-> "PENDING_UPDATE", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0],
      [seq |-> "496", refused |-> FALSE, a |-> <<"Updated", 1>>, status |-> "ACCEPTED", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0],
      [seq |-> "505", refused |-> FALSE, a |-> <<"Plain", "PENDING_UPDATE">>, status |-> "PENDING_UPDATE", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0],
      [seq |-> "511", refused |-> FALSE, a |-> <<"Updated", 1>>, status |-> "ACCEPTED", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0],
      [seq |-> "518", refused |-> FALSE, a |-> <<"Plain", "PENDING_UPDATE">>, status |-> "PENDING_UPDATE", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0],
      [seq |-> "522", refused |-> FALSE, a |-> <<"Updated", 1>>, status |-> "ACCEPTED", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0],
      [seq |-> "528", refused |-> FALSE, a |-> <<"Plain", "PENDING_UPDATE">>, status |-> "PENDING_UPDATE", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0],
      [seq |-> "534", refused |-> FALSE, a |-> <<"Updated", 1>>, status |-> "ACCEPTED", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0],
      [seq |-> "540", refused |-> FALSE, a |-> <<"Plain", "PENDING_CANCEL">>, status |-> "PENDING_CANCEL", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0],
      [seq |-> "542", refused |-> FALSE, a |-> <<"Fill", "T28", 1>>, status |-> "FILLED", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 1],
      [seq |-> "544", refused |-> TRUE, a |-> <<"Plain", "CANCEL_REJECTED">>, status |-> "FILLED", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 1]>>]
, [id |-> "golden-000001-0000001B", quantity |-> 1, steps |-> <<
      [seq |-> "480", refused |-> FALSE, a |-> <<"Plain", "SUBMITTED">>, status |-> "SUBMITTED", prev |-> "INITIALIZED", quantity |-> 1, filled |-> 0],
      [seq |-> "485", refused |-> FALSE, a |-> <<"Plain", "ACCEPTED">>, status |-> "ACCEPTED", prev |-> "SUBMITTED", quantity |-> 1, filled |-> 0],
      [seq |-> "486", refused |-> FALSE, a |-> <<"Plain", "EXPIRED">>, status |-> "EXPIRED", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0]>>]
, [id |-> "golden-000001-0000001C", quantity |-> 1, steps |-> <<
      [seq |-> "492", refused |-> FALSE, a |-> <<"Plain", "SUBMITTED">>, status |-> "SUBMITTED", prev |-> "INITIALIZED", quantity |-> 1, filled |-> 0],
      [seq |-> "498", refused |-> FALSE, a |-> <<"Plain", "ACCEPTED">>, status |-> "ACCEPTED", prev |-> "SUBMITTED", quantity |-> 1, filled |-> 0],
      [seq |-> "499", refused |-> FALSE, a |-> <<"Fill", "T25", 1>>, status |-> "FILLED", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 1]>>]
, [id |-> "golden-000001-0000001D", quantity |-> 1, steps |-> <<
      [seq |-> "518", refused |-> FALSE, a |-> <<"Plain", "SUBMITTED">>, status |-> "SUBMITTED", prev |-> "INITIALIZED", quantity |-> 1, filled |-> 0],
      [seq |-> "520", refused |-> FALSE, a |-> <<"Plain", "ACCEPTED">>, status |-> "ACCEPTED", prev |-> "SUBMITTED", quantity |-> 1, filled |-> 0],
      [seq |-> "528", refused |-> FALSE, a |-> <<"Plain", "PENDING_UPDATE">>, status |-> "PENDING_UPDATE", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0],
      [seq |-> "530", refused |-> FALSE, a |-> <<"Fill", "T27", 1>>, status |-> "FILLED", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 1],
      [seq |-> "532", refused |-> TRUE, a |-> <<"Plain", "MODIFY_REJECTED">>, status |-> "FILLED", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 1]>>]
, [id |-> "golden-000001-0000001E", quantity |-> 1, steps |-> <<
      [seq |-> "528", refused |-> FALSE, a |-> <<"Plain", "SUBMITTED">>, status |-> "SUBMITTED", prev |-> "INITIALIZED", quantity |-> 1, filled |-> 0],
      [seq |-> "535", refused |-> FALSE, a |-> <<"Plain", "REJECTED">>, status |-> "REJECTED", prev |-> "SUBMITTED", quantity |-> 1, filled |-> 0]>>]
, [id |-> "golden-000001-0000001F", quantity |-> 1, steps |-> <<
      [seq |-> "550", refused |-> FALSE, a |-> <<"Plain", "SUBMITTED">>, status |-> "SUBMITTED", prev |-> "INITIALIZED", quantity |-> 1, filled |-> 0],
      [seq |-> "552", refused |-> FALSE, a |-> <<"Plain", "ACCEPTED">>, status |-> "ACCEPTED", prev |-> "SUBMITTED", quantity |-> 1, filled |-> 0],
      [seq |-> "566", refused |-> FALSE, a |-> <<"Plain", "PENDING_UPDATE">>, status |-> "PENDING_UPDATE", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0],
      [seq |-> "570", refused |-> FALSE, a |-> <<"Updated", 1>>, status |-> "ACCEPTED", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0],
      [seq |-> "577", refused |-> FALSE, a |-> <<"Plain", "PENDING_UPDATE">>, status |-> "PENDING_UPDATE", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0],
      [seq |-> "579", refused |-> FALSE, a |-> <<"Fill", "T30", 1>>, status |-> "FILLED", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 1],
      [seq |-> "581", refused |-> TRUE, a |-> <<"Plain", "MODIFY_REJECTED">>, status |-> "FILLED", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 1]>>]
, [id |-> "golden-000001-0000001G", quantity |-> 1, steps |-> <<
      [seq |-> "550", refused |-> FALSE, a |-> <<"Plain", "SUBMITTED">>, status |-> "SUBMITTED", prev |-> "INITIALIZED", quantity |-> 1, filled |-> 0],
      [seq |-> "554", refused |-> FALSE, a |-> <<"Plain", "ACCEPTED">>, status |-> "ACCEPTED", prev |-> "SUBMITTED", quantity |-> 1, filled |-> 0],
      [seq |-> "566", refused |-> FALSE, a |-> <<"Plain", "PENDING_UPDATE">>, status |-> "PENDING_UPDATE", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0],
      [seq |-> "568", refused |-> FALSE, a |-> <<"Fill", "T29", 1>>, status |-> "FILLED", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 1],
      [seq |-> "571", refused |-> TRUE, a |-> <<"Plain", "MODIFY_REJECTED">>, status |-> "FILLED", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 1]>>]
, [id |-> "golden-000001-0000001H", quantity |-> 1, steps |-> <<
      [seq |-> "550", refused |-> FALSE, a |-> <<"Plain", "DENIED">>, status |-> "DENIED", prev |-> "INITIALIZED", quantity |-> 1, filled |-> 0]>>]
, [id |-> "golden-000001-0000001J", quantity |-> 1, steps |-> <<
      [seq |-> "577", refused |-> FALSE, a |-> <<"Plain", "SUBMITTED">>, status |-> "SUBMITTED", prev |-> "INITIALIZED", quantity |-> 1, filled |-> 0],
      [seq |-> "582", refused |-> FALSE, a |-> <<"Plain", "ACCEPTED">>, status |-> "ACCEPTED", prev |-> "SUBMITTED", quantity |-> 1, filled |-> 0],
      [seq |-> "590", refused |-> FALSE, a |-> <<"Fill", "T31", 1>>, status |-> "FILLED", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 1]>>]
, [id |-> "golden-000001-0000001K", quantity |-> 1, steps |-> <<
      [seq |-> "584", refused |-> FALSE, a |-> <<"Plain", "SUBMITTED">>, status |-> "SUBMITTED", prev |-> "INITIALIZED", quantity |-> 1, filled |-> 0],
      [seq |-> "586", refused |-> FALSE, a |-> <<"Plain", "ACCEPTED">>, status |-> "ACCEPTED", prev |-> "SUBMITTED", quantity |-> 1, filled |-> 0],
      [seq |-> "592", refused |-> FALSE, a |-> <<"Plain", "PENDING_UPDATE">>, status |-> "PENDING_UPDATE", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0],
      [seq |-> "594", refused |-> FALSE, a |-> <<"Updated", 1>>, status |-> "ACCEPTED", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0],
      [seq |-> "601", refused |-> FALSE, a |-> <<"Plain", "PENDING_CANCEL">>, status |-> "PENDING_CANCEL", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0],
      [seq |-> "603", refused |-> FALSE, a |-> <<"Fill", "T32", 1>>, status |-> "FILLED", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 1],
      [seq |-> "605", refused |-> TRUE, a |-> <<"Plain", "CANCEL_REJECTED">>, status |-> "FILLED", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 1]>>]
, [id |-> "golden-000001-0000001M", quantity |-> 1, steps |-> <<
      [seq |-> "592", refused |-> FALSE, a |-> <<"Plain", "SUBMITTED">>, status |-> "SUBMITTED", prev |-> "INITIALIZED", quantity |-> 1, filled |-> 0],
      [seq |-> "596", refused |-> FALSE, a |-> <<"Plain", "ACCEPTED">>, status |-> "ACCEPTED", prev |-> "SUBMITTED", quantity |-> 1, filled |-> 0],
      [seq |-> "601", refused |-> FALSE, a |-> <<"Plain", "PENDING_CANCEL">>, status |-> "PENDING_CANCEL", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0],
      [seq |-> "606", refused |-> FALSE, a |-> <<"Plain", "CANCELED">>, status |-> "CANCELED", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0]>>]
, [id |-> "golden-000001-0000001N", quantity |-> 1, steps |-> <<
      [seq |-> "613", refused |-> FALSE, a |-> <<"Plain", "SUBMITTED">>, status |-> "SUBMITTED", prev |-> "INITIALIZED", quantity |-> 1, filled |-> 0],
      [seq |-> "615", refused |-> FALSE, a |-> <<"Plain", "ACCEPTED">>, status |-> "ACCEPTED", prev |-> "SUBMITTED", quantity |-> 1, filled |-> 0],
      [seq |-> "622", refused |-> FALSE, a |-> <<"Plain", "PENDING_UPDATE">>, status |-> "PENDING_UPDATE", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0],
      [seq |-> "624", refused |-> FALSE, a |-> <<"Updated", 1>>, status |-> "ACCEPTED", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0],
      [seq |-> "638", refused |-> FALSE, a |-> <<"Plain", "PENDING_UPDATE">>, status |-> "PENDING_UPDATE", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0],
      [seq |-> "640", refused |-> FALSE, a |-> <<"Fill", "T34", 1>>, status |-> "FILLED", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 1],
      [seq |-> "642", refused |-> TRUE, a |-> <<"Plain", "MODIFY_REJECTED">>, status |-> "FILLED", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 1]>>]
, [id |-> "golden-000001-0000001P", quantity |-> 1, steps |-> <<
      [seq |-> "613", refused |-> FALSE, a |-> <<"Plain", "SUBMITTED">>, status |-> "SUBMITTED", prev |-> "INITIALIZED", quantity |-> 1, filled |-> 0],
      [seq |-> "617", refused |-> FALSE, a |-> <<"Plain", "ACCEPTED">>, status |-> "ACCEPTED", prev |-> "SUBMITTED", quantity |-> 1, filled |-> 0],
      [seq |-> "622", refused |-> FALSE, a |-> <<"Plain", "PENDING_UPDATE">>, status |-> "PENDING_UPDATE", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0],
      [seq |-> "625", refused |-> FALSE, a |-> <<"Updated", 1>>, status |-> "ACCEPTED", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0],
      [seq |-> "638", refused |-> FALSE, a |-> <<"Plain", "PENDING_UPDATE">>, status |-> "PENDING_UPDATE", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0],
      [seq |-> "644", refused |-> FALSE, a |-> <<"Updated", 1>>, status |-> "ACCEPTED", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0],
      [seq |-> "650", refused |-> FALSE, a |-> <<"Plain", "PENDING_UPDATE">>, status |-> "PENDING_UPDATE", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0],
      [seq |-> "653", refused |-> FALSE, a |-> <<"Updated", 1>>, status |-> "ACCEPTED", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0],
      [seq |-> "657", refused |-> FALSE, a |-> <<"Plain", "PENDING_UPDATE">>, status |-> "PENDING_UPDATE", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0],
      [seq |-> "662", refused |-> FALSE, a |-> <<"Updated", 1>>, status |-> "ACCEPTED", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0],
      [seq |-> "670", refused |-> FALSE, a |-> <<"Plain", "PENDING_UPDATE">>, status |-> "PENDING_UPDATE", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0],
      [seq |-> "672", refused |-> FALSE, a |-> <<"Fill", "T36", 1>>, status |-> "FILLED", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 1],
      [seq |-> "676", refused |-> TRUE, a |-> <<"Plain", "MODIFY_REJECTED">>, status |-> "FILLED", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 1]>>]
, [id |-> "golden-000001-0000001Q", quantity |-> 1, steps |-> <<
      [seq |-> "622", refused |-> FALSE, a |-> <<"Plain", "SUBMITTED">>, status |-> "SUBMITTED", prev |-> "INITIALIZED", quantity |-> 1, filled |-> 0],
      [seq |-> "627", refused |-> FALSE, a |-> <<"Plain", "ACCEPTED">>, status |-> "ACCEPTED", prev |-> "SUBMITTED", quantity |-> 1, filled |-> 0],
      [seq |-> "629", refused |-> FALSE, a |-> <<"Fill", "T33", 1>>, status |-> "FILLED", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 1]>>]
, [id |-> "golden-000001-0000001R", quantity |-> 1, steps |-> <<
      [seq |-> "638", refused |-> FALSE, a |-> <<"Plain", "SUBMITTED">>, status |-> "SUBMITTED", prev |-> "INITIALIZED", quantity |-> 1, filled |-> 0],
      [seq |-> "646", refused |-> FALSE, a |-> <<"Plain", "REJECTED">>, status |-> "REJECTED", prev |-> "SUBMITTED", quantity |-> 1, filled |-> 0]>>]
, [id |-> "golden-000001-0000001S", quantity |-> 1, steps |-> <<
      [seq |-> "650", refused |-> FALSE, a |-> <<"Plain", "SUBMITTED">>, status |-> "SUBMITTED", prev |-> "INITIALIZED", quantity |-> 1, filled |-> 0],
      [seq |-> "652", refused |-> FALSE, a |-> <<"Plain", "ACCEPTED">>, status |-> "ACCEPTED", prev |-> "SUBMITTED", quantity |-> 1, filled |-> 0],
      [seq |-> "657", refused |-> FALSE, a |-> <<"Plain", "PENDING_UPDATE">>, status |-> "PENDING_UPDATE", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0],
      [seq |-> "659", refused |-> FALSE, a |-> <<"Fill", "T35", 1>>, status |-> "FILLED", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 1],
      [seq |-> "661", refused |-> TRUE, a |-> <<"Plain", "MODIFY_REJECTED">>, status |-> "FILLED", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 1]>>]
, [id |-> "golden-000001-0000001T", quantity |-> 1, steps |-> <<
      [seq |-> "657", refused |-> FALSE, a |-> <<"Plain", "SUBMITTED">>, status |-> "SUBMITTED", prev |-> "INITIALIZED", quantity |-> 1, filled |-> 0],
      [seq |-> "663", refused |-> FALSE, a |-> <<"Plain", "ACCEPTED">>, status |-> "ACCEPTED", prev |-> "SUBMITTED", quantity |-> 1, filled |-> 0],
      [seq |-> "664", refused |-> FALSE, a |-> <<"Plain", "EXPIRED">>, status |-> "EXPIRED", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0]>>]
, [id |-> "golden-000001-0000001V", quantity |-> 1, steps |-> <<
      [seq |-> "670", refused |-> FALSE, a |-> <<"Plain", "SUBMITTED">>, status |-> "SUBMITTED", prev |-> "INITIALIZED", quantity |-> 1, filled |-> 0],
      [seq |-> "670", refused |-> FALSE, a |-> <<"Plain", "PENDING_UPDATE">>, status |-> "PENDING_UPDATE", prev |-> "SUBMITTED", quantity |-> 1, filled |-> 0],
      [seq |-> "674", refused |-> FALSE, a |-> <<"Plain", "ACCEPTED">>, status |-> "ACCEPTED", prev |-> "SUBMITTED", quantity |-> 1, filled |-> 0],
      [seq |-> "677", refused |-> FALSE, a |-> <<"Updated", 2>>, status |-> "ACCEPTED", prev |-> "ACCEPTED", quantity |-> 2, filled |-> 0],
      [seq |-> "679", refused |-> FALSE, a |-> <<"Plain", "PENDING_CANCEL">>, status |-> "PENDING_CANCEL", prev |-> "ACCEPTED", quantity |-> 2, filled |-> 0],
      [seq |-> "681", refused |-> FALSE, a |-> <<"Fill", "T37", 2>>, status |-> "FILLED", prev |-> "ACCEPTED", quantity |-> 2, filled |-> 2],
      [seq |-> "683", refused |-> TRUE, a |-> <<"Plain", "CANCEL_REJECTED">>, status |-> "FILLED", prev |-> "ACCEPTED", quantity |-> 2, filled |-> 2]>>]
, [id |-> "golden-000001-0000001W", quantity |-> 1, steps |-> <<
      [seq |-> "687", refused |-> FALSE, a |-> <<"Plain", "SUBMITTED">>, status |-> "SUBMITTED", prev |-> "INITIALIZED", quantity |-> 1, filled |-> 0],
      [seq |-> "689", refused |-> FALSE, a |-> <<"Plain", "ACCEPTED">>, status |-> "ACCEPTED", prev |-> "SUBMITTED", quantity |-> 1, filled |-> 0],
      [seq |-> "698", refused |-> FALSE, a |-> <<"Plain", "PENDING_UPDATE">>, status |-> "PENDING_UPDATE", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0],
      [seq |-> "700", refused |-> FALSE, a |-> <<"Fill", "T38", 1>>, status |-> "FILLED", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 1],
      [seq |-> "702", refused |-> TRUE, a |-> <<"Plain", "MODIFY_REJECTED">>, status |-> "FILLED", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 1]>>]
, [id |-> "golden-000001-0000001X", quantity |-> 1, steps |-> <<
      [seq |-> "687", refused |-> FALSE, a |-> <<"Plain", "SUBMITTED">>, status |-> "SUBMITTED", prev |-> "INITIALIZED", quantity |-> 1, filled |-> 0],
      [seq |-> "690", refused |-> FALSE, a |-> <<"Plain", "ACCEPTED">>, status |-> "ACCEPTED", prev |-> "SUBMITTED", quantity |-> 1, filled |-> 0],
      [seq |-> "698", refused |-> FALSE, a |-> <<"Plain", "PENDING_UPDATE">>, status |-> "PENDING_UPDATE", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0],
      [seq |-> "703", refused |-> FALSE, a |-> <<"Updated", 1>>, status |-> "ACCEPTED", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0],
      [seq |-> "708", refused |-> FALSE, a |-> <<"Plain", "PENDING_UPDATE">>, status |-> "PENDING_UPDATE", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0],
      [seq |-> "712", refused |-> FALSE, a |-> <<"Updated", 1>>, status |-> "ACCEPTED", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0],
      [seq |-> "717", refused |-> FALSE, a |-> <<"Plain", "PENDING_UPDATE">>, status |-> "PENDING_UPDATE", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0],
      [seq |-> "719", refused |-> FALSE, a |-> <<"Fill", "T39", 1>>, status |-> "FILLED", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 1],
      [seq |-> "722", refused |-> TRUE, a |-> <<"Plain", "MODIFY_REJECTED">>, status |-> "FILLED", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 1]>>]
, [id |-> "golden-000001-0000001Y", quantity |-> 1, steps |-> <<
      [seq |-> "708", refused |-> FALSE, a |-> <<"Plain", "SUBMITTED">>, status |-> "SUBMITTED", prev |-> "INITIALIZED", quantity |-> 1, filled |-> 0],
      [seq |-> "710", refused |-> FALSE, a |-> <<"Plain", "ACCEPTED">>, status |-> "ACCEPTED", prev |-> "SUBMITTED", quantity |-> 1, filled |-> 0],
      [seq |-> "717", refused |-> FALSE, a |-> <<"Plain", "PENDING_UPDATE">>, status |-> "PENDING_UPDATE", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0],
      [seq |-> "721", refused |-> FALSE, a |-> <<"Updated", 1>>, status |-> "ACCEPTED", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0],
      [seq |-> "724", refused |-> FALSE, a |-> <<"Plain", "PENDING_UPDATE">>, status |-> "PENDING_UPDATE", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0],
      [seq |-> "726", refused |-> FALSE, a |-> <<"Updated", 1>>, status |-> "ACCEPTED", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0],
      [seq |-> "739", refused |-> FALSE, a |-> <<"Plain", "PENDING_CANCEL">>, status |-> "PENDING_CANCEL", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0],
      [seq |-> "741", refused |-> FALSE, a |-> <<"Plain", "CANCELED">>, status |-> "CANCELED", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0]>>]
, [id |-> "golden-000001-0000001Z", quantity |-> 1, steps |-> <<
      [seq |-> "724", refused |-> FALSE, a |-> <<"Plain", "SUBMITTED">>, status |-> "SUBMITTED", prev |-> "INITIALIZED", quantity |-> 1, filled |-> 0],
      [seq |-> "727", refused |-> FALSE, a |-> <<"Plain", "ACCEPTED">>, status |-> "ACCEPTED", prev |-> "SUBMITTED", quantity |-> 1, filled |-> 0],
      [seq |-> "739", refused |-> FALSE, a |-> <<"Plain", "PENDING_CANCEL">>, status |-> "PENDING_CANCEL", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0],
      [seq |-> "743", refused |-> FALSE, a |-> <<"Plain", "CANCELED">>, status |-> "CANCELED", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0]>>]
, [id |-> "golden-000001-00000020", quantity |-> 1, steps |-> <<
      [seq |-> "731", refused |-> FALSE, a |-> <<"Plain", "DENIED">>, status |-> "DENIED", prev |-> "INITIALIZED", quantity |-> 1, filled |-> 0]>>]
, [id |-> "golden-000001-00000021", quantity |-> 1, steps |-> <<
      [seq |-> "745", refused |-> FALSE, a |-> <<"Plain", "SUBMITTED">>, status |-> "SUBMITTED", prev |-> "INITIALIZED", quantity |-> 1, filled |-> 0],
      [seq |-> "747", refused |-> FALSE, a |-> <<"Plain", "ACCEPTED">>, status |-> "ACCEPTED", prev |-> "SUBMITTED", quantity |-> 1, filled |-> 0],
      [seq |-> "755", refused |-> FALSE, a |-> <<"Plain", "PENDING_UPDATE">>, status |-> "PENDING_UPDATE", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0],
      [seq |-> "757", refused |-> FALSE, a |-> <<"Updated", 1>>, status |-> "ACCEPTED", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0],
      [seq |-> "763", refused |-> FALSE, a |-> <<"Plain", "PENDING_UPDATE">>, status |-> "PENDING_UPDATE", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0],
      [seq |-> "767", refused |-> FALSE, a |-> <<"Updated", 1>>, status |-> "ACCEPTED", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0],
      [seq |-> "775", refused |-> FALSE, a |-> <<"Plain", "PENDING_UPDATE">>, status |-> "PENDING_UPDATE", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0],
      [seq |-> "777", refused |-> FALSE, a |-> <<"Fill", "T42", 1>>, status |-> "FILLED", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 1],
      [seq |-> "779", refused |-> TRUE, a |-> <<"Plain", "MODIFY_REJECTED">>, status |-> "FILLED", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 1]>>]
, [id |-> "golden-000001-00000022", quantity |-> 1, steps |-> <<
      [seq |-> "745", refused |-> FALSE, a |-> <<"Plain", "SUBMITTED">>, status |-> "SUBMITTED", prev |-> "INITIALIZED", quantity |-> 1, filled |-> 0],
      [seq |-> "748", refused |-> FALSE, a |-> <<"Plain", "ACCEPTED">>, status |-> "ACCEPTED", prev |-> "SUBMITTED", quantity |-> 1, filled |-> 0],
      [seq |-> "755", refused |-> FALSE, a |-> <<"Plain", "PENDING_UPDATE">>, status |-> "PENDING_UPDATE", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0],
      [seq |-> "759", refused |-> FALSE, a |-> <<"Updated", 1>>, status |-> "ACCEPTED", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0],
      [seq |-> "763", refused |-> FALSE, a |-> <<"Plain", "PENDING_UPDATE">>, status |-> "PENDING_UPDATE", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0],
      [seq |-> "765", refused |-> FALSE, a |-> <<"Fill", "T41", 1>>, status |-> "FILLED", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 1],
      [seq |-> "768", refused |-> TRUE, a |-> <<"Plain", "MODIFY_REJECTED">>, status |-> "FILLED", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 1]>>]
, [id |-> "golden-000001-00000023", quantity |-> 1, steps |-> <<
      [seq |-> "745", refused |-> FALSE, a |-> <<"Plain", "SUBMITTED">>, status |-> "SUBMITTED", prev |-> "INITIALIZED", quantity |-> 1, filled |-> 0],
      [seq |-> "749", refused |-> FALSE, a |-> <<"Plain", "ACCEPTED">>, status |-> "ACCEPTED", prev |-> "SUBMITTED", quantity |-> 1, filled |-> 0],
      [seq |-> "751", refused |-> FALSE, a |-> <<"Fill", "T40", 1>>, status |-> "FILLED", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 1]>>]
, [id |-> "golden-000001-00000024", quantity |-> 1, steps |-> <<
      [seq |-> "775", refused |-> FALSE, a |-> <<"Plain", "SUBMITTED">>, status |-> "SUBMITTED", prev |-> "INITIALIZED", quantity |-> 1, filled |-> 0],
      [seq |-> "781", refused |-> FALSE, a |-> <<"Plain", "ACCEPTED">>, status |-> "ACCEPTED", prev |-> "SUBMITTED", quantity |-> 1, filled |-> 0],
      [seq |-> "794", refused |-> FALSE, a |-> <<"Plain", "PENDING_UPDATE">>, status |-> "PENDING_UPDATE", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0],
      [seq |-> "798", refused |-> FALSE, a |-> <<"Updated", 1>>, status |-> "ACCEPTED", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0],
      [seq |-> "802", refused |-> FALSE, a |-> <<"Plain", "PENDING_CANCEL">>, status |-> "PENDING_CANCEL", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0],
      [seq |-> "804", refused |-> FALSE, a |-> <<"Fill", "T43", 1>>, status |-> "FILLED", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 1],
      [seq |-> "806", refused |-> TRUE, a |-> <<"Plain", "CANCEL_REJECTED">>, status |-> "FILLED", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 1]>>]
, [id |-> "golden-000001-00000025", quantity |-> 1, steps |-> <<
      [seq |-> "787", refused |-> FALSE, a |-> <<"Plain", "SUBMITTED">>, status |-> "SUBMITTED", prev |-> "INITIALIZED", quantity |-> 1, filled |-> 0],
      [seq |-> "789", refused |-> FALSE, a |-> <<"Plain", "ACCEPTED">>, status |-> "ACCEPTED", prev |-> "SUBMITTED", quantity |-> 1, filled |-> 0],
      [seq |-> "794", refused |-> FALSE, a |-> <<"Plain", "PENDING_UPDATE">>, status |-> "PENDING_UPDATE", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0],
      [seq |-> "796", refused |-> FALSE, a |-> <<"Updated", 1>>, status |-> "ACCEPTED", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0],
      [seq |-> "802", refused |-> FALSE, a |-> <<"Plain", "PENDING_CANCEL">>, status |-> "PENDING_CANCEL", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0],
      [seq |-> "807", refused |-> FALSE, a |-> <<"Plain", "CANCELED">>, status |-> "CANCELED", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0]>>]
, [id |-> "golden-000001-00000026", quantity |-> 1, steps |-> <<
      [seq |-> "814", refused |-> FALSE, a |-> <<"Plain", "SUBMITTED">>, status |-> "SUBMITTED", prev |-> "INITIALIZED", quantity |-> 1, filled |-> 0],
      [seq |-> "816", refused |-> FALSE, a |-> <<"Plain", "ACCEPTED">>, status |-> "ACCEPTED", prev |-> "SUBMITTED", quantity |-> 1, filled |-> 0],
      [seq |-> "824", refused |-> FALSE, a |-> <<"Plain", "PENDING_UPDATE">>, status |-> "PENDING_UPDATE", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0],
      [seq |-> "828", refused |-> FALSE, a |-> <<"Updated", 1>>, status |-> "ACCEPTED", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0],
      [seq |-> "836", refused |-> FALSE, a |-> <<"Plain", "PENDING_UPDATE">>, status |-> "PENDING_UPDATE", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0],
      [seq |-> "838", refused |-> FALSE, a |-> <<"Updated", 1>>, status |-> "ACCEPTED", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0],
      [seq |-> "847", refused |-> FALSE, a |-> <<"Plain", "PENDING_UPDATE">>, status |-> "PENDING_UPDATE", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0],
      [seq |-> "849", refused |-> FALSE, a |-> <<"Fill", "T45", 1>>, status |-> "FILLED", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 1],
      [seq |-> "851", refused |-> TRUE, a |-> <<"Plain", "MODIFY_REJECTED">>, status |-> "FILLED", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 1]>>]
, [id |-> "golden-000001-00000027", quantity |-> 1, steps |-> <<
      [seq |-> "814", refused |-> FALSE, a |-> <<"Plain", "SUBMITTED">>, status |-> "SUBMITTED", prev |-> "INITIALIZED", quantity |-> 1, filled |-> 0],
      [seq |-> "818", refused |-> FALSE, a |-> <<"Plain", "ACCEPTED">>, status |-> "ACCEPTED", prev |-> "SUBMITTED", quantity |-> 1, filled |-> 0],
      [seq |-> "824", refused |-> FALSE, a |-> <<"Plain", "PENDING_UPDATE">>, status |-> "PENDING_UPDATE", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0],
      [seq |-> "826", refused |-> FALSE, a |-> <<"Fill", "T44", 1>>, status |-> "FILLED", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 1],
      [seq |-> "830", refused |-> TRUE, a |-> <<"Plain", "MODIFY_REJECTED">>, status |-> "FILLED", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 1]>>]
, [id |-> "golden-000001-00000028", quantity |-> 1, steps |-> <<
      [seq |-> "814", refused |-> FALSE, a |-> <<"Plain", "SUBMITTED">>, status |-> "SUBMITTED", prev |-> "INITIALIZED", quantity |-> 1, filled |-> 0],
      [seq |-> "819", refused |-> FALSE, a |-> <<"Plain", "ACCEPTED">>, status |-> "ACCEPTED", prev |-> "SUBMITTED", quantity |-> 1, filled |-> 0],
      [seq |-> "820", refused |-> FALSE, a |-> <<"Plain", "EXPIRED">>, status |-> "EXPIRED", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0]>>]
, [id |-> "golden-000001-00000029", quantity |-> 1, steps |-> <<
      [seq |-> "836", refused |-> FALSE, a |-> <<"Plain", "SUBMITTED">>, status |-> "SUBMITTED", prev |-> "INITIALIZED", quantity |-> 1, filled |-> 0],
      [seq |-> "840", refused |-> FALSE, a |-> <<"Plain", "ACCEPTED">>, status |-> "ACCEPTED", prev |-> "SUBMITTED", quantity |-> 1, filled |-> 0],
      [seq |-> "847", refused |-> FALSE, a |-> <<"Plain", "PENDING_UPDATE">>, status |-> "PENDING_UPDATE", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0],
      [seq |-> "852", refused |-> FALSE, a |-> <<"Updated", 1>>, status |-> "ACCEPTED", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0],
      [seq |-> "861", refused |-> FALSE, a |-> <<"Plain", "PENDING_UPDATE">>, status |-> "PENDING_UPDATE", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0],
      [seq |-> "864", refused |-> FALSE, a |-> <<"Updated", 1>>, status |-> "ACCEPTED", prev |-> "ACCEPTED", quantity |-> 1, filled |-> 0]>>]
, [id |-> "golden-000001-0000002A", quantity |-> 1, steps |-> <<
      [seq |-> "847", refused |-> FALSE, a |-> <<"Plain", "SUBMITTED">>, status |-> "SUBMITTED", prev |-> "INITIALIZED", quantity |-> 1, filled |-> 0],
      [seq |-> "853", refused |-> FALSE, a |-> <<"Plain", "REJECTED">>, status |-> "REJECTED", prev |-> "SUBMITTED", quantity |-> 1, filled |-> 0]>>]
, [id |-> "golden-000001-0000002B", quantity |-> 1, steps |-> <<
      [seq |-> "861", refused |-> FALSE, a |-> <<"Plain", "SUBMITTED">>, status |-> "SUBMITTED", prev |-> "INITIALIZED", quantity |-> 1, filled |-> 0],
      [seq |-> "863", refused |-> FALSE, a |-> <<"Plain", "ACCEPTED">>, status |-> "ACCEPTED", prev |-> "SUBMITTED", quantity |-> 1, filled |-> 0]>>]
>>

Do(a) == CASE a[1] = "Plain" -> Plain(a[2])
         []   a[1] = "Updated" -> Updated(a[2])
         []   a[1] = "Fill" -> Fill(a[2], a[3])
         []   a[1] = "Void" -> Void(a[2], a[3])

Fresh(q) == /\ status' = "INITIALIZED" /\ prev' = "NONE" /\ quantity' = q
            /\ filled' = 0 /\ fills' = [t \in {} |-> 0]

TraceInit == /\ o = 1 /\ k = 0
             /\ status = "INITIALIZED" /\ prev = "NONE"
             /\ quantity = Orders[1].quantity /\ filled = 0 /\ fills = [t \in {} |-> 0]

Replay == /\ k < Len(Orders[o].steps)
          /\ LET s == Orders[o].steps[k + 1] IN
               /\ IF s.refused THEN ~ENABLED Do(s.a) /\ UNCHANGED vars ELSE Do(s.a)
               /\ status' = s.status /\ prev' = s.prev
               /\ quantity' = s.quantity /\ filled' = s.filled
          /\ k' = k + 1
          /\ UNCHANGED o

NextOrder == /\ k = Len(Orders[o].steps) /\ o < Len(Orders)
             /\ o' = o + 1 /\ k' = 0 /\ Fresh(Orders[o + 1].quantity)

Done == /\ k = Len(Orders[o].steps) /\ o = Len(Orders) /\ UNCHANGED <<vars, o, k>>

TraceNext == Replay \/ NextOrder \/ Done

=============================================================================
