#!/usr/bin/env python3
"""Generates the model crate's nautilus conformance data from tests/conformance/nautilus_<commit>.json.

Writes two files (both checked in, regenerated when the JSON changes):
  crates/kernel/jarvis-model/src/generated/currencies.rs   the built-in currency table
  crates/kernel/jarvis-model/tests/generated/vectors.rs    enum values, strings, aliases, constants
The kernel takes no dependencies, so the JSON is turned into Rust here rather than parsed in a test.
"""
from __future__ import annotations

import json
import pathlib
import shutil
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
SRC = ROOT / "tests/conformance/nautilus_cd417b80.json"
CURRENCIES = ROOT / "rust/crates/kernel/jarvis-model/src/generated/currencies.rs"
VECTORS = ROOT / "rust/crates/kernel/jarvis-model/tests/generated/vectors.rs"

# The enums the model crate defines (docs/architecture.md section 6.6). The conformance file has a
# few more that jarvis does not use; they are listed so the test can state the omission.
MODEL_ENUMS = [
    "AccountType", "AggregationSource", "AggressorSide", "AssetClass", "BarAggregation",
    "BarIntervalType", "BookAction", "BookType", "ContingencyType", "CurrencyType",
    "InstrumentClass", "InstrumentCloseType", "LiquiditySide", "MarketStatus",
    "MarketStatusAction", "OmsType", "OptionKind", "OrderSide", "OrderStatus", "OrderType",
    "PositionAdjustmentType", "PositionSide", "PriceType", "RecordFlag", "TimeInForce",
    "TradingState", "TrailingOffsetType", "TriggerType",
]


def main() -> int:
    data = json.loads(SRC.read_text(encoding="utf-8"))
    commit = data["source"]["commit"]
    header = f"// Generated by rust/tools/gen_conformance.py from {SRC.relative_to(ROOT)} (nautilus_trader {commit[:8]}).\n// Do not edit; rerun the script.\n"

    lines = [header, "use crate::currency::{Currency, CurrencyType};", "",
             "/// The currencies `nautilus_trader` defines, in its order.",
             "pub(crate) const BUILTIN: &[Currency] = &["]
    for c in data["currencies"]:
        lines.append(
            f'    Currency::builtin("{c["code"]}", {c["precision"]}, {c["iso4217"]}, "{c["name"]}", CurrencyType::{c["type"]}),'
        )
    lines += ["];", ""]
    CURRENCIES.write_text("\n".join(lines), encoding="utf-8")

    v = [header, "#![allow(dead_code, unreachable_pub, clippy::unreadable_literal)]", "",
         "pub struct EnumVariant { pub name: &'static str, pub value: i64, pub string: &'static str, pub aliases: &'static [&'static str] }",
         "pub struct EnumVectors { pub name: &'static str, pub case_insensitive: bool, pub variants: &'static [EnumVariant] }", ""]
    v.append("pub const ENUMS: &[EnumVectors] = &[")
    for name in MODEL_ENUMS:
        e = data["enums"][name]
        v.append(f'    EnumVectors {{ name: "{name}", case_insensitive: {str(e.get("case_insensitive", False)).lower()}, variants: &[')
        for var in e["variants"]:
            aliases = ", ".join(f'"{a}"' for a in var.get("aliases", []))
            v.append(f'        EnumVariant {{ name: "{var["name"]}", value: {var["value"]}, string: "{var["string"]}", aliases: &[{aliases}] }},')
        v.append("    ] },")
    v.append("];")
    v.append("")
    unused = sorted(set(data["enums"]) - set(MODEL_ENUMS))
    v.append("/// Enums in the conformance file that the jarvis model does not define.")
    v.append("pub const UNUSED_ENUMS: &[&str] = &[" + ", ".join(f'"{n}"' for n in unused) + "];")
    v.append("")
    v.append("pub const LEGACY_NONE_TOKENS: &[(&str, &str)] = &[" + ", ".join(f'("{k}", "{val}")' for k, val in data["legacy_none_tokens"].items()) + "];")
    v.append("")
    c = data["constants"]
    v.append(f"pub const FIXED_PRECISION: u8 = {int(c['FIXED_PRECISION'])};")
    for k in ["PRICE_MAX", "PRICE_MIN", "QUANTITY_MAX", "QUANTITY_MIN", "MONEY_MAX", "MONEY_MIN"]:
        v.append(f"pub const {k}_INTEGRAL: i64 = {int(c[k])};")
    v.append("")
    v.append("pub struct CurrencyVector { pub code: &'static str, pub precision: u8, pub iso4217: u16, pub name: &'static str, pub currency_type: &'static str }")
    v.append("pub const CURRENCIES: &[CurrencyVector] = &[")
    for cur in data["currencies"]:
        v.append(f'    CurrencyVector {{ code: "{cur["code"]}", precision: {cur["precision"]}, iso4217: {cur["iso4217"]}, name: "{cur["name"]}", currency_type: "{cur["type"]}" }},')
    v.append("];")
    v.append("")
    v.append("pub const STRUCT_FIELDS: &[(&str, &[&str])] = &[")
    for name, fields in data["structs"].items():
        v.append(f'    ("{name}", &[' + ", ".join(f'"{f}"' for f in fields) + "]),")
    v.append("];")
    v.append("")
    VECTORS.parent.mkdir(parents=True, exist_ok=True)
    VECTORS.write_text("\n".join(v), encoding="utf-8")
    # The outputs are formatted so that `cargo fmt --check` and the CI up-to-date check agree.
    if shutil.which("rustfmt"):
        subprocess.run(["rustfmt", "--edition", "2021", str(CURRENCIES), str(VECTORS)], check=True)
    print(f"wrote {CURRENCIES.relative_to(ROOT)} ({len(data['currencies'])} currencies) and {VECTORS.relative_to(ROOT)} ({len(MODEL_ENUMS)} enums)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
