[package]
name = "node"
description = "Build info, node configuration, node composition, command-line entry points"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
kernel-core.workspace = true
model.workspace = true
engine.workspace = true
backtest.workspace = true
sys.workspace = true
