[package]
name = "execution"
description = "Order core, order state machine, OMS, execution engine and algorithms, reconciliation"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
kernel-core.workspace = true
model.workspace = true
data.workspace = true
cost.workspace = true
portfolio.workspace = true
