#!/usr/bin/env python3
"""Generate the nautilus-compatible enum and currency tables from the conformance snapshot.

    tools/gen_model_tables.py           # write jarvis/model/generated/{enums,currencies}.hpp
                                        # and python/src/generated/enums.cpp
    tools/gen_model_tables.py --check   # fail if the generated headers are stale

Input: tests/conformance/nautilus_<commit>.json (tools/nautilus_snapshot.py). Generating the
tables instead of typing them keeps the integer values and strings identical to nautilus
(docs/architecture.md section 6.6).
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
SNAPSHOT = REPO_ROOT / "tests" / "conformance" / "nautilus_cd417b80.json"
OUT_DIR = REPO_ROOT / "jarvis" / "model" / "generated"
PY_OUT_DIR = REPO_ROOT / "python" / "src" / "generated"

# C++ enumerator names that would collide with jarvis type names. The string form is unchanged.
CPP_RENAMES = {("TrailingOffsetType", "Price"): "PriceUnits"}


def cpp_name(enum: str, variant: str) -> str:
    return CPP_RENAMES.get((enum, variant), variant)


def header(title: str, commit: str) -> list[str]:
    return [
        "#pragma once",
        "",
        f"// {title}",
        f"// Generated by tools/gen_model_tables.py from nautilus_trader {commit[:8]}; do not edit.",
        "",
    ]


def cpp_string(text: str) -> str:
    return '"' + text.replace("\\", "\\\\").replace('"', '\\"') + '"'


def render_enums(snapshot: dict) -> str:
    commit = snapshot["source"]["commit"]
    legacy = snapshot["legacy_none_tokens"]
    out = header("nautilus-compatible enums: integer values, strings and parsing.", commit)
    out += [
        "#include <array>",
        "#include <cstddef>",
        "#include <cstdint>",
        "#include <optional>",
        "#include <string_view>",
        "",
        '#include "jarvis/core/status.hpp"',
        "",
        "namespace jarvis::model {",
        "",
        "namespace detail {",
        "",
        "[[nodiscard]] constexpr bool iequals(std::string_view a, std::string_view b) noexcept {",
        "  if (a.size() != b.size()) {",
        "    return false;",
        "  }",
        "  for (std::size_t i = 0; i < a.size(); ++i) {",
        "    const char x = a[i] >= 'a' && a[i] <= 'z' ? static_cast<char>(a[i] - 32) : a[i];",
        "    const char y = b[i] >= 'a' && b[i] <= 'z' ? static_cast<char>(b[i] - 32) : b[i];",
        "    if (x != y) {",
        "      return false;",
        "    }",
        "  }",
        "  return true;",
        "}",
        "",
        "} // namespace detail",
        "",
    ]
    for name, enum in snapshot["enums"].items():
        variants = enum["variants"]
        out.append(f"enum class {name} : std::uint8_t {{")
        for v in variants:
            renamed = cpp_name(name, v["name"])
            note = f" // nautilus {name}::{v['name']}" if renamed != v["name"] else ""
            out.append(f"  {renamed} = {v['value']},{note}")
        out.append("};")
        out.append("")
        values = ", ".join(f"{name}::{cpp_name(name, v['name'])}" for v in variants)
        out.append(f"inline constexpr std::array<{name}, {len(variants)}> k{name}Values = {{{values}}};")
        out.append("")
        out.append(f"[[nodiscard]] constexpr std::string_view to_string({name} value) noexcept {{")
        out.append("  switch (value) {")
        for v in variants:
            out.append(f"  case {name}::{cpp_name(name, v['name'])}:")
            out.append(f"    return {cpp_string(v['string'])};")
        out.append("  }")
        out.append('  return "";')
        out.append("}")
        out.append("")
        out.append(
            f"[[nodiscard]] constexpr core::Status parse(std::string_view text, {name}& out) noexcept {{"
        )
        for v in variants:
            names = [v["string"], *v["aliases"]]
            condition = " || ".join(f"detail::iequals(text, {cpp_string(n)})" for n in names)
            out.append(f"  if ({condition}) {{")
            out.append(f"    out = {name}::{cpp_name(name, v['name'])};")
            out.append("    return core::Status::Ok;")
            out.append("  }")
        out.append("  return core::Status::ParseError;")
        out.append("}")
        out.append("")
        out.append(
            f"[[nodiscard]] constexpr core::Status from_value(std::uint8_t value, {name}& out) noexcept {{"
        )
        out.append("  switch (value) {")
        for v in variants:
            out.append(f"  case {v['value']}:")
            out.append(f"    out = {name}::{cpp_name(name, v['name'])};")
            out.append("    return core::Status::Ok;")
        out.append("  default:")
        out.append("    return core::Status::OutOfRange;")
        out.append("  }")
        out.append("}")
        out.append("")
        if name in legacy:
            token = legacy[name]
            out.append(f"// Accepts the legacy token {token} as \"no value\", like nautilus.")
            out.append(
                f"[[nodiscard]] constexpr core::Status parse_optional(std::string_view text,"
                f" std::optional<{name}>& out) noexcept {{"
            )
            out.append(f"  if (text.empty() || detail::iequals(text, {cpp_string(token)})) {{")
            out.append("    out = std::nullopt;")
            out.append("    return core::Status::Ok;")
            out.append("  }")
            out.append(f"  {name} value{{}};")
            out.append("  const core::Status status = parse(text, value);")
            out.append("  if (core::ok(status)) {")
            out.append("    out = value;")
            out.append("  }")
            out.append("  return status;")
            out.append("}")
            out.append("")
    names = list(snapshot["enums"])
    out += [
        "// Name-based access for tools and bindings: parse a value of the enum called `enum_name`.",
        "struct EnumValueText {",
        "  std::string_view string;",
        "  std::uint8_t value = 0;",
        "};",
        "",
        "namespace detail {",
        "",
        "template <typename E>",
        "[[nodiscard]] constexpr core::Status parse_as(std::string_view text, EnumValueText& out) noexcept {",
        "  E value{};",
        "  const core::Status status = parse(text, value);",
        "  if (core::ok(status)) {",
        "    out = EnumValueText{to_string(value), static_cast<std::uint8_t>(value)};",
        "  }",
        "  return status;",
        "}",
        "",
        "} // namespace detail",
        "",
        "struct EnumParser {",
        "  std::string_view name;",
        "  core::Status (*parse)(std::string_view text, EnumValueText& out) noexcept;",
        "};",
        "",
        f"inline constexpr std::array<EnumParser, {len(names)}> kEnumParsers = {{{{",
        *[f"    {{{cpp_string(n)}, &detail::parse_as<{n}>}}," for n in names],
        "}};",
        "",
        "// NotFound when no enum has that name; ParseError when the text is not one of its values.",
        "[[nodiscard]] constexpr core::Status parse_enum_by_name(std::string_view enum_name,",
        "                                                        std::string_view text,",
        "                                                        EnumValueText& out) noexcept {",
        "  for (const EnumParser& parser : kEnumParsers) {",
        "    if (parser.name == enum_name) {",
        "      return parser.parse(text, out);",
        "    }",
        "  }",
        "  return core::Status::NotFound;",
        "}",
        "",
    ]
    out += ["} // namespace jarvis::model", ""]
    return "\n".join(out)


def render_currencies(snapshot: dict) -> str:
    commit = snapshot["source"]["commit"]
    currencies = snapshot["currencies"]
    out = header("Built-in currencies of nautilus_trader (code, precision, ISO 4217, name, type).", commit)
    out += [
        "#include <array>",
        "#include <cstdint>",
        "#include <string_view>",
        "",
        '#include "jarvis/model/generated/enums.hpp"',
        "",
        "namespace jarvis::model {",
        "",
        "struct BuiltinCurrency {",
        "  std::string_view code;",
        "  std::uint8_t precision;",
        "  std::uint16_t iso4217;",
        "  std::string_view name;",
        "  CurrencyType type;",
        "};",
        "",
        f"inline constexpr std::array<BuiltinCurrency, {len(currencies)}> kBuiltinCurrencies = {{{{",
    ]
    for c in currencies:
        out.append(
            f"    {{{cpp_string(c['code'])}, {c['precision']}, {c['iso4217']}, "
            f"{cpp_string(c['name'])}, CurrencyType::{c['type']}}},"
        )
    out += ["}};", "", "} // namespace jarvis::model", ""]
    return "\n".join(out)


# Enums whose values combine as bit flags; Python sees them as arithmetic enums.
ARITHMETIC_ENUMS = {"RecordFlag"}


def render_enum_bindings(snapshot: dict) -> str:
    commit = snapshot["source"]["commit"]
    out = [
        f"// Python bindings of the nautilus-compatible enums.",
        f"// Generated by tools/gen_model_tables.py from nautilus_trader {commit[:8]}; do not edit.",
        "",
        "#include <string_view>",
        "",
        "#include <nanobind/nanobind.h>",
        "#include <nanobind/stl/string_view.h>",
        "",
        '#include "../common.hpp"',
        '#include "jarvis/model/generated/enums.hpp"',
        "",
        "namespace jarvis::py {",
        "",
        "void bind_generated_enums(nb::module_& mod) {",
    ]
    for name, enum in snapshot["enums"].items():
        extra = ", nb::is_arithmetic()" if name in ARITHMETIC_ENUMS else ""
        out.append(f'  nb::enum_<m::{name}>(mod, "{name}"{extra})')
        for v in enum["variants"]:
            py_name = v["string"]
            if not py_name.isidentifier():
                raise SystemExit(f"{name}.{v['name']}: '{py_name}' is not a Python identifier")
            out.append(f'      .value("{py_name}", m::{name}::{cpp_name(name, v["name"])})')
        out.append(
            f'      .def_static("from_str", [](std::string_view text) '
            f'{{ return parse_enum<m::{name}>(text, "{name}"); }});'
        )
    out += ["}", "", "} // namespace jarvis::py", ""]
    return "\n".join(out)


def outputs() -> dict[Path, str]:
    snapshot = json.loads(SNAPSHOT.read_text())
    return {
        OUT_DIR / "enums.hpp": render_enums(snapshot),
        OUT_DIR / "currencies.hpp": render_currencies(snapshot),
        PY_OUT_DIR / "enums.cpp": render_enum_bindings(snapshot),
    }


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)
    stale = []
    for path, content in outputs().items():
        current = path.read_text() if path.exists() else None
        if current == content:
            continue
        if args.check:
            stale.append(path.relative_to(REPO_ROOT).as_posix())
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content)
    if stale:
        print("stale generated files (run tools/gen_model_tables.py): " + ", ".join(stale))
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
